version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: task-db
    networks:
      - taskManager-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: task-manager:latest
    build: .
    container_name: app
    networks:
      - taskManager-network
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy

networks:
  taskManager-network:
    driver: bridge
